"use client";
import { Provider as ReduxProvider } from "react-redux";
import ThemeWrapper from "../layout/ThemeWrapper";
import Provider from "../providers/ChakraProvider";
import { store } from "../store";
import "../styles/global.css";

// export const metadata = {
//   title: "Sport Empire",
//   description: "Generated by Next.js",
// };
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider store={store}>
      <html lang="en">
        <head>
          <title>Sport Empire</title>
          <meta name="sportEmpire" content="sportEmpire" />
        </head>
        <body suppressHydrationWarning={true}>
          <Provider>
            <ThemeWrapper>{children}</ThemeWrapper>
          </Provider>
        </body>
      </html>
    </ReduxProvider>
  );
}
